version: '3.8'
services:
  api:
    build:
      context: ./
      target: 'develop-stage'
    container_name: rust-api
    command: sh -c "cargo watch -x run"
    tty: true
    working_dir: '/src'
    volumes:
      - .:/src/:cached
    expose:
      - '8080'
    ports:
      - '8080:8080'